<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.2.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="block block-blog block-layered-nav block-m-hide">
    <?php echo $this->getChildHtml('blog_tags'); ?>
</div>
<script type="text/javascript">
if($j( document ).width() < '992'){
	$j('.block.block-m-hide .block-title').click(function() {
		var subEL = $j(this).next('.block-content');
		if(subEL.is(':hidden')){
			subEL.slideDown();
			$j(this).addClass('active');	
		}
		else{
			subEL.slideUp();
			$j(this).removeClass('active');		
		}
	});
}
</script>