<?php
 /*
 * @category   Mageho
 * @package    Mageho_Sortproducts
 * @copyright  Copyright (c) 2012  Mageho (http://www.mageho.com)
 * @license    http://www.mageho.com/license  Proprietary License
 * @version    1.0.0
 */
?>
<div class="entry-edit">
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Sort Products'); ?></h4>
    	<div class="form-buttons"></div>
	</div>

	<div class="fieldset">
		<iframe id="sortproductsdraganddrop" src="<?php echo $this->getSortProductsUrl(); ?>" width="100%" height="500" scrolling="yes" allowtransparency="true" frameborder="0" style="overflow:auto;"></iframe>
	</div>
</div>