<?php
$mediaDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'media/theme/';
$themeDirection = Mage::getStoreConfig('webthemeoptions/general/appthemedir');
//Categories Block
$showCats = Mage::getStoreConfig('webthemeoptions/homecats/enable');
//recipes
$showRe = Mage::getStoreConfig('webthemeoptions/homere/enable');
//about
$homeabout = Mage::getStoreConfig('webthemeoptions/homeabout/enable');
$aboutTitle = Mage::getStoreConfig('webthemeoptions/homeabout/titletext');
$aboutText = Mage::getStoreConfig('webthemeoptions/homeabout/text');
$aboutLink = Mage::getStoreConfig('webthemeoptions/homeabout/link');
$aboutBanner = Mage::getStoreConfig('webthemeoptions/homeabout/banner');
//How works Block
$showHowWorks = Mage::getStoreConfig('webthemeoptions/howworks/enable');
$Workstitleimg = Mage::getStoreConfig('webthemeoptions/howworks/titleimg');
$Workstitletext = Mage::getStoreConfig('webthemeoptions/howworks/titletext');
$titletextsub = Mage::getStoreConfig('webthemeoptions/howworks/titletextsub');
//first
$works1banner = Mage::getStoreConfig('webthemeoptions/howworks/works1banner');
$works1text = Mage::getStoreConfig('webthemeoptions/howworks/works1text');
$works1sub = Mage::getStoreConfig('webthemeoptions/howworks/works1sub');
//second
$works2banner = Mage::getStoreConfig('webthemeoptions/howworks/works2banner');
$works2text = Mage::getStoreConfig('webthemeoptions/howworks/works2text');
$works2sub = Mage::getStoreConfig('webthemeoptions/howworks/works2sub');
//third
$works3banner = Mage::getStoreConfig('webthemeoptions/howworks/works3banner');
$works3text = Mage::getStoreConfig('webthemeoptions/howworks/works3text');
$works3sub = Mage::getStoreConfig('webthemeoptions/howworks/works3sub');
//fours
$works4banner = Mage::getStoreConfig('webthemeoptions/howworks/works4banner');
$works4text = Mage::getStoreConfig('webthemeoptions/howworks/works4text');
$works4sub = Mage::getStoreConfig('webthemeoptions/howworks/works4sub');
//blog
$showBlog = Mage::getStoreConfig('webthemeoptions/blog/enable');
//get customer and load wishlist
$customerId = null;
$wishlist = null;
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $customerId = $customer->getId();
}
if (isset($customerId) && $customerId) {
    $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true);
}
?>
<?php echo $this->getChildHtml('banner') ?>
<?php if($showCats): ?>
	<div class="home-block home-cats">
		<div class="container">
			<?php echo $this->getChildHtml('cats-homepage'); ?>	
		</div>
	</div>
<?php endif; ?>
<?php if($showRe): ?>
	<div class="home-block home-cats home-re">
		<div class="container">
			<?php echo $this->getChildHtml('recipes-homepage'); ?>	
		</div>
	</div>
<?php endif; ?>
<?php if($homeabout): ?>
	<div class="home-block homeabout home-cats">
		<div class="container">
			<div class="row">				
				<div class="item col-md-12 col-xs-12 about-text">
					<h3><?php echo $aboutTitle; ?></h3>
					<p>
						<?php echo $aboutText; ?>
						<a href="<?php echo $aboutLink; ?>"><?php echo $this->__('Read More'); ?> >></a>
					</p>
				</div>
				<div class="item img col-md-12 col-xs-12"><img src="<?php echo $mediaDir . $aboutBanner; ?>" alt="<?php echo $aboutTitle ?>" /></div>				
			</div>
		</div>
	</div>
<?php endif; ?>
<?php if($showHowWorks): ?>
	<div class="home-block how-works">
		<div class="container">
			<div class="title">
				<h3><?php echo $Workstitletext; ?></h3>
				<p><?php echo $titletextsub; ?></p>
			</div>		
			<div class="row">
				<div class="item col-md-3 col-xs-6 first">
					<div class="block">
						<div class="banner">
							<img src="<?php echo $mediaDir . $works1banner; ?>" alt="<?php echo $works1text ?>" />
						</div>
						<div class="text">
							<h3><?php echo $works1text ?></h3>
							<div class="subTitle"><?php echo $works1sub ?></div>
						</div>
					</div>
				</div>
				<div class="item col-md-3 col-xs-6 second">
					<div class="block">
						<div class="banner">
							<img src="<?php echo $mediaDir . $works2banner; ?>" alt="<?php echo $works2text ?>" />
						</div>
						<div class="text">
							<h3><?php echo $works2text ?></h3>
							<div class="subTitle"><?php echo $works2sub ?></div>
						</div>						
					</div>
				</div>
				<div class="item col-md-3 col-xs-6 third">
					<div class="block">
						<div class="banner">
							<img src="<?php echo $mediaDir . $works3banner; ?>" alt="<?php echo $works3text ?>" />
						</div>
						<div class="text">
							<h3><?php echo $works3text ?></h3>
							<div class="subTitle"><?php echo $works3sub ?></div>
						</div>						
					</div>
				</div>
				<div class="item col-md-3 col-xs-6 fours">
					<div class="block">
						<div class="banner">
							<img src="<?php echo $mediaDir . $works4banner; ?>" alt="<?php echo $works4text ?>" />
						</div>
						<div class="text">							
							<h3><?php echo $works4text ?></h3>
							<div class="subTitle"><?php echo $works4sub ?></div>
						</div>						
					</div>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
<?php if($showBlog): ?>
	<?php echo $this->getChildHtml('blog-homepage'); ?>	
<?php endif; ?>