<?php
$_zoom_w = Mage::getStoreConfig('prozoom/prozoom_config/zoom_w');
$_zoom_h = Mage::getStoreConfig('prozoom/prozoom_config/zoom_h');
$_border_w = Mage::getStoreConfig('prozoom/prozoom_config/zoom_border_w');
$_border_color = Mage::getStoreConfig('prozoom/prozoom_config/zoom_border_color');
$_lightbox_w = Mage::getStoreConfig('prozoom/prozoom_config/lightbox_w');
$_lightbox_h = Mage::getStoreConfig('prozoom/prozoom_config/lightbox_h');
$_thumbnail_qty = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_qty');
$_thumbnail_w = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_w');
$_thumbnail_h = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_h');
$_scroll_qty = Mage::getStoreConfig('prozoom/prozoom_config/scroll_qty');
$_auto = Mage::getStoreConfig('prozoom/prozoom_config/auto_scroll');
$themeDirection = Mage::getStoreConfig('themeoptions/general/themedir');
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$themeDirection = Mage::getStoreConfig('webthemeoptions/general/appthemedir');
$showInsta = $_product->getShow_insta();
$video = $_product->getVideo_code();
?>
	<?php $_images = $this->getGalleryImages(); ?>
	<div class="product-img-box main-image slider-big-img-wrap">
		<?php
			$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(689,530).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		?>
		<!-- images for lightbox -->
		<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_lightbox_w, $_lightbox_h); ?>" class = "ma-a-lighbox" rel="lightbox[rotation]"></a>
		<!--++++++++++++-->
		<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class = "cloud-zoom" id="ma-zoom1" style="position: relative;" rel="position: 'inside', adjustX:10, adjustY:-2, zoomWidth:<?php echo $_zoom_w; ?>, zoomHeight:<?php echo $_zoom_h; ?>">
			<?php echo $_helper->productAttribute($_product, $_img, 'image'); ?>
		</a>
	</div>
	<?php if ( count($this->getGalleryImages()) > 0 ): ?>
		<div class="product-img-box more-images slider-small-img-wrap">
			<div class="more-views ma-thumbnail-container owl-carousel">
					<?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
						<div class="item <?php if($i==0): ?>selected<?php endif; ?>">
							<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1200,1200); ?>" class="cloud-zoom-gallery" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" name="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
								rel="useZoom: 'ma-zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(689,530); ?>'">
								<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(140,106); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
							</a>
						</div>
					<?php $i++; endforeach; ?>
			</div>
		</div>
	<?php endif; ?>	
		<script type="text/javascript">
			$j(document).ready(function() {		
				$j('.more-views').owlCarousel({
					nav:true,
					dots:false,
					autoplay : false,
					autoplayHoverPause : true,
					singleItem:true,
					pagination:false,
					navigation:true,
					lazyLoad : false,
					<?php if($themeDirection == 'rtl'): ?>
					rtl:true,
					<?php endif; ?>
					loop:false,
					margin : 20,
					responsive:{
						0:{
							items:1
						},
						768:{
							items:3
						},
						992:{
							items:4
						}
					}
				});
			});
		</script>			