<?php
	$themeDirection = Mage::getStoreConfig('webthemeoptions/general/appthemedir');
	$_product = $this->getProduct();
	$related_ar = $_product->getRelatedRecipes();
	$ar_arr=explode(",",$related_ar);
?>
<?php if($related_ar): ?>
<div class="block-related recipes-related">
	<div class="container">
		<div class="recipes-homepage">
			<div class="title"><?php echo $this->__('Related Recipes') ?></div>
					<div class="blog-home re-blog">
						<div class="home-blog-content">
							<div id="owl-recipes" class="owl-carousel">
							<?php foreach ($ar_arr as $_product): ?>
								<?php $_product= Mage::getModel('catalog/product')->load($_product); ?>
								<div class="item">
									<div class="product-image-basket">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(337,365); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
										</a>
									</div>	
									<div class="name-price">
										<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $_product->getName(); ?></a></p>
										<a class="read-re" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Read Recipe'); ?> >></a>
									</div>							
								</div>
							<?php endforeach; ?>
							</div>
						</div> 
					</div> 
				<script type="text/javascript">
					$j( document ).ready(function() {
						$j("#owl-recipes").owlCarousel({
							nav:true,
							autoplay : false,
							autoplayHoverPause : true,
							singleItem:true,
							pagination:false,
							navigation:true,
							lazyLoad : false,
							loop:true,
							dots:false,
							<?php if($themeDirection == 'rtl'): ?>
							rtl:true,
							<?php endif; ?>	
							margin :1,
							autoWidth:false,
							responsive:{
								0:{
									items:1
								},
								768:{
									items:1
								},					
								992:{
									items:1
								}			
							}
						});		
					});
				</script>
		</div>
	</div>
</div>
<?php endif; ?>