<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Layerednavigation
 * @version    1.3.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php /** @var AW_Layerednavigation_Block_Layer $this */ ?>
<?php if($this->canShowBlock()): ?>
    <div class="block block-layered-nav" id="aw-ln-filters">
        <div class="block-content toggle-content">
            <script type="text/javascript">
                var awLnUpdaterInstance = new awLnUpdater();
            </script>
            <div class="block-subtitle block-subtitle--filter"><span><?php echo $this->__('Filter By') ?></span></div>
            <dl id="aw-ln-filters-container" class="aw-ln-filters-container">
                <?php foreach ($this->getFilterList() as $_filter): ?>
                    <?php if($this->getItemCountByFilter($_filter)): ?>
						<div class="layered-block attr-<?php echo $_filter->getCode(); ?>">
							<?php if($_filter->getCode() != 'cosher'): ?>
								<dt>
									<span><?php echo $_filter->getTitle() ?></span>
								</dt>
							<?php endif; ?>
							<dd>
								<?php echo $this->renderFilter($_filter); ?>
							</dd>
						</div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">
                <?php foreach ($this->getFilterList() as $_filter): ?>
                    <?php if($this->getItemCountByFilter($_filter) == 0): ?>
                        awLnUpdaterInstance.registerNoItemsFilterCode(<?php echo Zend_Json::encode($_filter->getCode());?>);
                    <?php endif; ?>
                <?php endforeach; ?>
            </script>

            <script type="text/javascript">
                decorateDataList('aw-ln-filters-container');
                //decorateDataList('aw-ln-filters');
                awLnUpdaterInstance.init({
                    layerContainerElSelector: ".block-layered-nav",
                    productsContainerElSelectorList: [".category-view", ".results-view", ".category-products", ".category_cms_block"],
                    emptyProductsContainerElSelectorList: [".note-msg"],
                    toolbarContainerElSelectorList: [
                        ".category-view .toolbar",
                        ".results-view .toolbar",
                        ".category-products .toolbar"
                    ],
                    clearAllElSelector: '.aw-ln-clear-all',
                    clearFilterElSelector: '.aw-ln-filter-clear',
                    isAjax: <?php echo Zend_Json::encode($this->isAjax());?>,
                    canAddNonFilteredParams: <?php echo Zend_Json::encode($this->canAddNonFilteredParams());?>,
                    overlaySettings: <?php echo Zend_Json::encode($this->getOverlaySettings());?>,
                    overlayCssClass: 'aw-ln-overlay',
                    searchQueryParamCode: <?php echo Zend_Json::encode($this->getSearchQueryParamCode());?>
                });
            </script>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
		$j('.block-layered-nav dt').click(function() {
			var subEL = $j(this).next('dd');
			if(subEL.is(':hidden')){
				subEL.slideDown();
				$j(this).addClass('active');	
			}
			else{
				subEL.slideUp();
				$j(this).removeClass('active');		
			}	
		});
</script>