<form id="opc-discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post">
    <div class="discount">
        <div class="discount-form">    
			<label for="coupon_code"><?php echo $this->__('Do you have a coupon code?') ?></label>    
            <div class="input-box">
                <input class="input-text" id="coupon_code" type="text" placeholder="<?php echo $this->__('Enter the coupon code') ?>" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" autocomplete="off"/>
            </div>
            <div class="button-set">                
                <?php if(strlen($this->getCouponCode())): ?>
                    <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button remove-coupon couponButton"  value="<?php echo $this->__('Cancel') ?>"><?php echo $this->__('Cancel') ?></button>
				<?php else: ?>
					<button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button apply-coupon couponButton"  value="<?php echo $this->__('Apply Coupon') ?>"><?php echo $this->__('Apply Coupon') ?></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>