<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view product-view-quick">
    <div class="product-essential">
		<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
                    <div class="name-price">
						<div class="product-name product-name-view">
							<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
						</div>
                        <div class="price-info" <?php if($_product->getProduct_type()): ?>style="display:none;"<?php endif; ?>>
                            <?php echo $this->getPriceHtml($_product); ?>
                            <?php echo $this->getChildHtml('bundle_prices') ?>
                            <?php echo $this->getTierPriceHtml() ?>
                        </div>                        
                    </div>
                    <?php echo $this->getChildHtml('other'); ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif; ?>
                    <div class="extra-info">
                        <?php echo $this->getChildHtml('product_type_availability'); ?>
                    </div>
					<?php echo $this->getChildHtml('alert_urls') ?>					
                    <div class="add-to-cart-wrapper">
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getChildHtml('extrahint') ?>
                        <?php if (!$this->hasOptions()): ?>
                            <div class="add-to-box <?php if($_product->getTypeID() == 'giftcards'): ?>gitf-add<?php endif; ?>">
                                <?php if ($_product->isSaleable() || $_product->getTypeID() == 'giftcards'): ?>
                                    <?php echo $this->getChildHtml('addtocart') ?>
                                <?php endif; ?>
                            </div>
                            <?php echo $this->getChildHtml('extra_buttons') ?>
                        <?php endif; ?>
                    </div> 					
                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif; ?>	
					<div class="under-btn"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('under-btn')->toHtml(); ?></div>	
					<div class="view-page"><a href="<?php echo $_product->getProductUrl() ?>" target="_parent"><?php echo $this->__('Go to Full Details'); ?> >></a></div>
		</form>			
	</div>
</div>
<div style="display: none;" id="price-pop" class="price-pop">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pricing-popup')->toHtml() ?>
</div>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function (button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function (button, url) {
                if (this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
	<script type="text/javascript">
$j(document).ready(function() {
	//data popups
	$j(".under-btn a,.product-shop .description li a").fancybox({
		'hideOnContentClick': true,
		maxWidth:600
	});	
});
</script>